src/Mondial.DotNet.Web/Controllers/ContractController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mondial.DotNet.Web.Models;
using Mondial.DotNet.Library.Models;
using Mondial.DotNet.Library.Repositories.InMemory;
using Mondial.DotNet.Library.Repositories.Interfaces;
using Mondial.DotNet.Web.Controllers.Base;

namespace Mondial.DotNet.Web.Controllers
{
    public class ContractController : BaseController<Contract, IContractRepository>
    {

        public ContractController(IContractRepository repository) : base(repository)
        {
            
        }

        public override IActionResult Index() => View(Repository.GetAll().OrderBy(contract => contract.YearFrom));
    }
}

src/Mondial.DotNet.Web/Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mondial.DotNet.Web.Models;
using Mondial.DotNet.Library.Models;
using Mondial.DotNet.Library.Repositories.InMemory;
using Mondial.DotNet.Library.Repositories.Interfaces;
using System.Dynamic;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Mondial.DotNet.Web.Controllers.Base;

namespace Mondial.DotNet.Web.Controllers
{
    public class MapController : BaseDataController
    {
         public MapController(IContractRepository contractRepository, IPlayerRepository playerRepository, ITeamRepository teamRepository) : base(contractRepository, playerRepository, teamRepository)
        {

        }

        public IActionResult Index() => View(_teamRepository.GetAll()
                .Select(team => new { team.Name, team.Flag, team.Latitude, team.Longitude, team.Address, contracts = team.ContractCollection.OrderBy(contract => contract.YearFrom).Join(
                    _playerRepository.GetAll(), contract => contract.Signatory, player => player,
                    (contract, player) => new {yearFrom = contract.YearFrom, yearTo = contract.YearTo, lastname = player.LastName, firstname = player.FirstName}.ToExpando())
                    }.ToExpando()));
    }

    public static class Extensions
    {
        public static ExpandoObject ToExpando(this object anonymousObject)
        {
            IDictionary<string, object> anonymousDictionary = HtmlHelper.AnonymousObjectToHtmlAttributes(anonymousObject);
            IDictionary<string, object> expando = new ExpandoObject();
            foreach (var item in anonymousDictionary)
                expando.Add(item);
            return (ExpandoObject)expando;
        }
    }
}

src/Mondial.DotNet.Web/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mondial.DotNet.Web.Models;
using Mondial.DotNet.Library.Models;
using Mondial.DotNet.Library.Repositories.InMemory;
using Mondial.DotNet.Library.Repositories.Interfaces;
using Mondial.DotNet.Web.Controllers.Base;

namespace Mondial.DotNet.Web.Controllers
{
    public class PlayerController : BaseController<Player, IPlayerRepository>
    {

        public PlayerController(IPlayerRepository repository) : base(repository)
        {
            
        }

        public override IActionResult Index() => View(Repository.GetAll().OrderBy(player => player.LastName));
    }
}

src/Mondial.DotNet.Web/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mondial.DotNet.Web.Models;
using Mondial.DotNet.Library.Models;
using Mondial.DotNet.Library.Repositories.InMemory;
using Mondial.DotNet.Library.Repositories.Interfaces;
using Mondial.DotNet.Web.Controllers.Base;

namespace Mondial.DotNet.Web.Controllers
{
    public class TeamController : BaseController<Team, ITeamRepository>
    {

        public TeamController(ITeamRepository repository) : base(repository)
        {
            
        }

        public override IActionResult Index() => View(Repository.GetAll().OrderBy(team => team.Name));
    }
}

src/Mondial.DotNet.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Équipe de France - Mondial 2019</title>
    <link rel="shortcut icon" type="image/ico" href="/cdm.ico"> 
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("leaflet", false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">⚽ Mondial 2019</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Accueil</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Joueuses</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="Player" asp-action="Index">Toutes</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-controller="Player" asp-action="Edit">Ajouter...</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Clubs</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="Team" asp-action="Index">Tous</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-controller="Team" asp-action="Edit">Ajouter...</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Contrats</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="Contract" asp-action="Index">Tous</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-controller="Contract" asp-action="Edit">Ajouter...</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Map" asp-action="Index">Cartographie <span class="badge badge-pill badge-danger">New</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <!--<partial name="_CookieConsentPartial" />-->
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2019 - Julien Pons
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>